### ISSUE TITLE
README와 동작이 다르네요

### ISSUE THREAD

**Issue by ryanking13** [Jhuni0123/Jh-bot#1]
https://github.com/Jhuni0123/flareon-bot/blob/3ce48cbf450d678456dee120e5507f1d83a32390/bot.py#L89

`regex/부우*스으*터어*/`가 아니라 `regex/부우*스터어*/` 로 되어 있네요.

**Comment by Jhuni0123** [comment]
헉 실수했네요 ㅠㅠ 업데이트 했습니다.
